### PR TITLE
About, experience, connect sections added to the index.html

### PR DESCRIPTION
**Pull request by Carlivats**
I have very little experience with HTML, so it is not the best code, but I tried to make it good enough with external resources. 
Let me know how it looks!

### CODE REVIEW

**Comment by fee3fitri** [comment]
Hey Carlos, it looks good!

**Comment by fee3fitri** [comment]
In response to your question:

"On the step of adding my name to the README file, I did it on GitHub but then realized that maybe the instructions were to do it directly from the text editor on my computer. I noticed this until I already pushed the code to GitHub, and I tried to push it again, but nothing would happen, what should I do in a case like that?"

Did you stage and commit your work locally before you pushed it to Github?

**Comment by Carlivats** [comment]
Hi! I am sorry for the late response
I added the "mailto:" before the email, it makes much more sense now, Thank you!
And I did staged it and committed it before pushing it, but the first time. Is it a requirement to stage and commit again to make new changes?
Also, I am going to merge the pull request, and I am not sure if you will still be able to answer this question, but just in case you can't I will ask on the next assignment.

**Comment by fee3fitri** [comment]
Hey Carlos, yes it's required to stage and commit anytime you make a change. That way, Git tracks the changes you intend to include in your next push. Let me know if you still have any lingering questions about git.

**Pull request merged**
